using RenewalWebsite.Data;
using RenewalWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RenewalWebsite
{
    public class CountrySeeder
    {
        private readonly ApplicationDbContext _context;

        public CountrySeeder(ApplicationDbContext context)
        {
            _context = context;
        }

        public void Seed()
        {
            try
            {
                if (_context.Country.Count() == 0)
                {
                    _context.Country.Add(new Country() { CountryChinese = "阿富汗", CountryEnglish = "Afghanistan", ShortCode = "AF" });
                    _context.Country.Add(new Country() { CountryChinese = "荷兰", CountryEnglish = "Netherlands", ShortCode = "NL" });
                    _context.Country.Add(new Country() { CountryChinese = "荷属安的列斯群岛", CountryEnglish = "Netherlands Antilles", ShortCode = "AN" });
                    _context.Country.Add(new Country() { CountryChinese = "新喀里多尼亚", CountryEnglish = "New Caledonia", ShortCode = "NC" });
                    _context.Country.Add(new Country() { CountryChinese = "新西兰", CountryEnglish = "New Zealand", ShortCode = "NZ" });
                    _context.Country.Add(new Country() { CountryChinese = "尼加拉瓜", CountryEnglish = "Nicaragua", ShortCode = "NI" });
                    _context.Country.Add(new Country() { CountryChinese = "尼日尔", CountryEnglish = "Niger", ShortCode = "NE" });
                    _context.Country.Add(new Country() { CountryChinese = "尼日利亚", CountryEnglish = "Nigeria", ShortCode = "NG" });
                    _context.Country.Add(new Country() { CountryChinese = "纽埃", CountryEnglish = "Niue", ShortCode = "NU" });
                    _context.Country.Add(new Country() { CountryChinese = "诺福克岛", CountryEnglish = "Norfolk Island", ShortCode = "NF" });
                    _context.Country.Add(new Country() { CountryChinese = "北马里亚纳群岛", CountryEnglish = "Northern Mariana Islands", ShortCode = "MP" });
                    _context.Country.Add(new Country() { CountryChinese = "挪威", CountryEnglish = "Norway", ShortCode = "NO" });
                    _context.Country.Add(new Country() { CountryChinese = "阿曼", CountryEnglish = "Oman", ShortCode = "OM" });
                    _context.Country.Add(new Country() { CountryChinese = "尼泊尔", CountryEnglish = "Nepal", ShortCode = "NP" });
                    _context.Country.Add(new Country() { CountryChinese = "巴基斯坦", CountryEnglish = "Pakistan", ShortCode = "PK" });
                    _context.Country.Add(new Country() { CountryChinese = "巴拿马", CountryEnglish = "Panama", ShortCode = "PA" });
                    _context.Country.Add(new Country() { CountryChinese = "巴布亚新几内亚", CountryEnglish = "Papua New Guinea", ShortCode = "PG" });
                    _context.Country.Add(new Country() { CountryChinese = "巴拉圭", CountryEnglish = "Paraguay", ShortCode = "PY" });
                    _context.Country.Add(new Country() { CountryChinese = "秘鲁", CountryEnglish = "Peru", ShortCode = "PE" });
                    _context.Country.Add(new Country() { CountryChinese = "菲律宾", CountryEnglish = "Philippines", ShortCode = "PH" });
                    _context.Country.Add(new Country() { CountryChinese = "皮特凯恩", CountryEnglish = "Pitcairn", ShortCode = "PN" });
                    _context.Country.Add(new Country() { CountryChinese = "波兰", CountryEnglish = "Poland", ShortCode = "PL" });
                    _context.Country.Add(new Country() { CountryChinese = "葡萄牙", CountryEnglish = "Portugal", ShortCode = "PT" });
                    _context.Country.Add(new Country() { CountryChinese = "波多黎各", CountryEnglish = "Puerto Rico", ShortCode = "PR" });
                    _context.Country.Add(new Country() { CountryChinese = "卡塔尔", CountryEnglish = "Qatar", ShortCode = "QA" });
                    _context.Country.Add(new Country() { CountryChinese = "留尼旺", CountryEnglish = "Reunion", ShortCode = "RE" });
                    _context.Country.Add(new Country() { CountryChinese = "罗马尼亚", CountryEnglish = "Romania", ShortCode = "RO" });
                    _context.Country.Add(new Country() { CountryChinese = "帕劳", CountryEnglish = "Palau", ShortCode = "PW" });
                    _context.Country.Add(new Country() { CountryChinese = "俄罗斯联邦", CountryEnglish = "Russian Federation", ShortCode = "RU" });
                    _context.Country.Add(new Country() { CountryChinese = "瑙鲁", CountryEnglish = "Nauru", ShortCode = "NR" });
                    _context.Country.Add(new Country() { CountryChinese = "缅甸", CountryEnglish = "Myanmar", ShortCode = "MM" });
                    _context.Country.Add(new Country() { CountryChinese = "利比里亚", CountryEnglish = "Liberia", ShortCode = "LR" });
                    _context.Country.Add(new Country() { CountryChinese = "阿拉伯利比亚民众国", CountryEnglish = "Libyan Arab Jamahiriya", ShortCode = "LY" });
                    _context.Country.Add(new Country() { CountryChinese = "列支敦士登", CountryEnglish = "Liechtenstein", ShortCode = "LI" });
                    _context.Country.Add(new Country() { CountryChinese = "立陶宛", CountryEnglish = "Lithuania", ShortCode = "LT" });
                    _context.Country.Add(new Country() { CountryChinese = "卢森堡", CountryEnglish = "Luxembourg", ShortCode = "LU" });
                    _context.Country.Add(new Country() { CountryChinese = "澳门", CountryEnglish = "Macau", ShortCode = "MO" });
                    _context.Country.Add(new Country() { CountryChinese = "马其顿, 前南斯拉夫共和国", CountryEnglish = "Macedonia, The Former Yugoslav Republic of", ShortCode = "MK" });
                    _context.Country.Add(new Country() { CountryChinese = "马达加斯加", CountryEnglish = "Madagascar", ShortCode = "MG" });
                    _context.Country.Add(new Country() { CountryChinese = "马拉维", CountryEnglish = "Malawi", ShortCode = "MW" });
                    _context.Country.Add(new Country() { CountryChinese = "马来西亚", CountryEnglish = "Malaysia", ShortCode = "MY" });
                    _context.Country.Add(new Country() { CountryChinese = "马尔代夫", CountryEnglish = "Maldives", ShortCode = "MV" });
                    _context.Country.Add(new Country() { CountryChinese = "马里", CountryEnglish = "Mali", ShortCode = "ML" });
                    _context.Country.Add(new Country() { CountryChinese = "纳米比亚", CountryEnglish = "Namibia", ShortCode = "NA" });
                    _context.Country.Add(new Country() { CountryChinese = "马耳他", CountryEnglish = "Malta", ShortCode = "MT" });
                    _context.Country.Add(new Country() { CountryChinese = "马提尼克岛", CountryEnglish = "Martinique", ShortCode = "MQ" });
                    _context.Country.Add(new Country() { CountryChinese = "毛里塔尼亚", CountryEnglish = "Mauritania", ShortCode = "MR" });
                    _context.Country.Add(new Country() { CountryChinese = "毛里求斯", CountryEnglish = "Mauritius", ShortCode = "MU" });
                    _context.Country.Add(new Country() { CountryChinese = "马约特岛", CountryEnglish = "Mayotte", ShortCode = "YT" });
                    _context.Country.Add(new Country() { CountryChinese = "墨西哥", CountryEnglish = "Mexico", ShortCode = "MX" });
                    _context.Country.Add(new Country() { CountryChinese = "密克罗尼西亚、联邦", CountryEnglish = "Micronesia, Federated States of", ShortCode = "FM" });
                    _context.Country.Add(new Country() { CountryChinese = "摩尔多瓦共和国", CountryEnglish = "Moldova, Republic of", ShortCode = "MD" });
                    _context.Country.Add(new Country() { CountryChinese = "摩纳哥", CountryEnglish = "Monaco", ShortCode = "MC" });
                    _context.Country.Add(new Country() { CountryChinese = "蒙古", CountryEnglish = "Mongolia", ShortCode = "MN" });
                    _context.Country.Add(new Country() { CountryChinese = "蒙特塞拉特", CountryEnglish = "Montserrat", ShortCode = "MS" });
                    _context.Country.Add(new Country() { CountryChinese = "摩洛哥", CountryEnglish = "Morocco", ShortCode = "MA" });
                    _context.Country.Add(new Country() { CountryChinese = "莫桑比克", CountryEnglish = "Mozambique", ShortCode = "MZ" });
                    _context.Country.Add(new Country() { CountryChinese = "马绍尔群岛", CountryEnglish = "Marshall Islands", ShortCode = "MH" });
                    _context.Country.Add(new Country() { CountryChinese = "莱索托", CountryEnglish = "Lesotho", ShortCode = "LS" });
                    _context.Country.Add(new Country() { CountryChinese = "卢旺达", CountryEnglish = "Rwanda", ShortCode = "RW" });
                    _context.Country.Add(new Country() { CountryChinese = "圣卢西亚", CountryEnglish = "Saint LUCIA", ShortCode = "LC" });
                    _context.Country.Add(new Country() { CountryChinese = "多哥", CountryEnglish = "Togo", ShortCode = "TG" });
                    _context.Country.Add(new Country() { CountryChinese = "托克劳", CountryEnglish = "Tokelau", ShortCode = "TK" });
                    _context.Country.Add(new Country() { CountryChinese = "汤加", CountryEnglish = "Tonga", ShortCode = "TO" });
                    _context.Country.Add(new Country() { CountryChinese = "特立尼达和多巴哥", CountryEnglish = "Trinidad and Tobago", ShortCode = "TT" });
                    _context.Country.Add(new Country() { CountryChinese = "突尼斯", CountryEnglish = "Tunisia", ShortCode = "TN" });
                    _context.Country.Add(new Country() { CountryChinese = "土耳其", CountryEnglish = "Turkey", ShortCode = "TR" });
                    _context.Country.Add(new Country() { CountryChinese = "土库曼斯坦", CountryEnglish = "Turkmenistan", ShortCode = "TM" });
                    _context.Country.Add(new Country() { CountryChinese = "特克斯和凯科斯群岛", CountryEnglish = "Turks and Caicos Islands", ShortCode = "TC" });
                    _context.Country.Add(new Country() { CountryChinese = "图瓦卢", CountryEnglish = "Tuvalu", ShortCode = "TV" });
                    _context.Country.Add(new Country() { CountryChinese = "乌干达", CountryEnglish = "Uganda", ShortCode = "UG" });
                    _context.Country.Add(new Country() { CountryChinese = "乌克兰", CountryEnglish = "Ukraine", ShortCode = "UA" });
                    _context.Country.Add(new Country() { CountryChinese = "阿拉伯联合酋长国", CountryEnglish = "United Arab Emirates", ShortCode = "AE" });
                    _context.Country.Add(new Country() { CountryChinese = "泰国", CountryEnglish = "Thailand", ShortCode = "TH" });
                    _context.Country.Add(new Country() { CountryChinese = "英国", CountryEnglish = "United Kingdom", ShortCode = "GB" });
                    _context.Country.Add(new Country() { CountryChinese = "美国次要离岛", CountryEnglish = "United States Minor Outlying Islands", ShortCode = "UM" });
                    _context.Country.Add(new Country() { CountryChinese = "乌拉圭", CountryEnglish = "Uruguay", ShortCode = "UY" });
                    _context.Country.Add(new Country() { CountryChinese = "乌兹别克斯坦", CountryEnglish = "Uzbekistan", ShortCode = "UZ" });
                    _context.Country.Add(new Country() { CountryChinese = "瓦努阿图", CountryEnglish = "Vanuatu", ShortCode = "VU" });
                    _context.Country.Add(new Country() { CountryChinese = "委内瑞拉", CountryEnglish = "Venezuela", ShortCode = "VE" });
                    _context.Country.Add(new Country() { CountryChinese = "越南", CountryEnglish = "Viet Nam", ShortCode = "VN" });
                    _context.Country.Add(new Country() { CountryChinese = "维京群岛 (英国)", CountryEnglish = "Virgin Islands (British)", ShortCode = "VG" });
                    _context.Country.Add(new Country() { CountryChinese = "维京群岛 (美国)", CountryEnglish = "Virgin Islands (U.S.)", ShortCode = "VI" });
                    _context.Country.Add(new Country() { CountryChinese = "沃利斯和富图纳群岛", CountryEnglish = "Wallis and Futuna Islands", ShortCode = "WF" });
                    _context.Country.Add(new Country() { CountryChinese = "西撒哈拉", CountryEnglish = "Western Sahara", ShortCode = "EH" });
                    _context.Country.Add(new Country() { CountryChinese = "也门", CountryEnglish = "Yemen", ShortCode = "YE" });
                    _context.Country.Add(new Country() { CountryChinese = "南斯拉夫", CountryEnglish = "Yugoslavia", ShortCode = "YU" });
                    _context.Country.Add(new Country() { CountryChinese = "美国", CountryEnglish = "United States", ShortCode = "US" });
                    _context.Country.Add(new Country() { CountryChinese = "圣基茨和尼维斯", CountryEnglish = "Saint Kitts and Nevis", ShortCode = "KN" });
                    _context.Country.Add(new Country() { CountryChinese = "坦桑尼亚联合共和国", CountryEnglish = "Tanzania, United Republic of", ShortCode = "TZ" });
                    _context.Country.Add(new Country() { CountryChinese = "中国台湾省", CountryEnglish = "Taiwan, Province of China", ShortCode = "TW" });
                    _context.Country.Add(new Country() { CountryChinese = "圣文森特和格林纳丁斯", CountryEnglish = "Saint Vincent and the Grenadines", ShortCode = "VC" });
                    _context.Country.Add(new Country() { CountryChinese = "萨摩亚", CountryEnglish = "Samoa", ShortCode = "WS" });
                    _context.Country.Add(new Country() { CountryChinese = "圣马力诺", CountryEnglish = "San Marino", ShortCode = "SM" });
                    _context.Country.Add(new Country() { CountryChinese = "圣多美和普林西比", CountryEnglish = "Sao Tome and Principe", ShortCode = "ST" });
                    _context.Country.Add(new Country() { CountryChinese = "沙特阿拉伯", CountryEnglish = "Saudi Arabia", ShortCode = "SA" });
                    _context.Country.Add(new Country() { CountryChinese = "塞内加尔", CountryEnglish = "Senegal", ShortCode = "SN" });
                    _context.Country.Add(new Country() { CountryChinese = "塞舌尔", CountryEnglish = "Seychelles", ShortCode = "SC" });
                    _context.Country.Add(new Country() { CountryChinese = "塞拉利昂", CountryEnglish = "Sierra Leone", ShortCode = "SL" });
                    _context.Country.Add(new Country() { CountryChinese = "新加坡", CountryEnglish = "Singapore", ShortCode = "SG" });
                    _context.Country.Add(new Country() { CountryChinese = "斯洛伐克 (斯洛伐克共和国)", CountryEnglish = "Slovakia (Slovak Republic)", ShortCode = "SK" });
                    _context.Country.Add(new Country() { CountryChinese = "斯洛文尼亚", CountryEnglish = "Slovenia", ShortCode = "SI" });
                    _context.Country.Add(new Country() { CountryChinese = "所罗门群岛", CountryEnglish = "Solomon Islands", ShortCode = "SB" });
                    _context.Country.Add(new Country() { CountryChinese = "塔吉克斯坦", CountryEnglish = "Tajikistan", ShortCode = "TJ" });
                    _context.Country.Add(new Country() { CountryChinese = "索马里", CountryEnglish = "Somalia", ShortCode = "SO" });
                    _context.Country.Add(new Country() { CountryChinese = "南乔治亚岛和南三明治群岛", CountryEnglish = "South Georgia and the South Sandwich Islands", ShortCode = "GS" });
                    _context.Country.Add(new Country() { CountryChinese = "西班牙", CountryEnglish = "Spain", ShortCode = "ES" });
                    _context.Country.Add(new Country() { CountryChinese = "斯里兰卡", CountryEnglish = "Sri Lanka", ShortCode = "LK" });
                    _context.Country.Add(new Country() { CountryChinese = "圣赫勒拿", CountryEnglish = "St. Helena", ShortCode = "SH" });
                    _context.Country.Add(new Country() { CountryChinese = "圣皮埃尔和圣皮埃尔", CountryEnglish = "St. Pierre and Miquelon", ShortCode = "PM" });
                    _context.Country.Add(new Country() { CountryChinese = "苏丹", CountryEnglish = "Sudan", ShortCode = "SD" });
                    _context.Country.Add(new Country() { CountryChinese = "苏里南", CountryEnglish = "Suriname", ShortCode = "SR" });
                    _context.Country.Add(new Country() { CountryChinese = "斯瓦尔巴特和扬马延岛", CountryEnglish = "Svalbard and Jan Mayen Islands", ShortCode = "SJ" });
                    _context.Country.Add(new Country() { CountryChinese = "斯威士兰", CountryEnglish = "Swaziland", ShortCode = "SZ" });
                    _context.Country.Add(new Country() { CountryChinese = "瑞典", CountryEnglish = "Sweden", ShortCode = "SE" });
                    _context.Country.Add(new Country() { CountryChinese = "瑞士", CountryEnglish = "Switzerland", ShortCode = "CH" });
                    _context.Country.Add(new Country() { CountryChinese = "阿拉伯叙利亚共和国", CountryEnglish = "Syrian Arab Republic", ShortCode = "SY" });
                    _context.Country.Add(new Country() { CountryChinese = "南非", CountryEnglish = "South Africa", ShortCode = "ZA" });
                    _context.Country.Add(new Country() { CountryChinese = "赞比亚", CountryEnglish = "Zambia", ShortCode = "ZM" });
                    _context.Country.Add(new Country() { CountryChinese = "黎巴嫩", CountryEnglish = "Lebanon", ShortCode = "LB" });
                    _context.Country.Add(new Country() { CountryChinese = "老挝人民民主共和国", CountryEnglish = "Lao People's Democratic Republic", ShortCode = "LA" });
                    _context.Country.Add(new Country() { CountryChinese = "文莱达鲁萨兰国", CountryEnglish = "Brunei Darussalam", ShortCode = "BN" });
                    _context.Country.Add(new Country() { CountryChinese = "保加利亚", CountryEnglish = "Bulgaria", ShortCode = "BG" });
                    _context.Country.Add(new Country() { CountryChinese = "布基纳法索", CountryEnglish = "Burkina Faso", ShortCode = "BF" });
                    _context.Country.Add(new Country() { CountryChinese = "布隆迪", CountryEnglish = "Burundi", ShortCode = "BI" });
                    _context.Country.Add(new Country() { CountryChinese = "柬埔寨", CountryEnglish = "Cambodia", ShortCode = "KH" });
                    _context.Country.Add(new Country() { CountryChinese = "喀麦隆", CountryEnglish = "Cameroon", ShortCode = "CM" });
                    _context.Country.Add(new Country() { CountryChinese = "加拿大", CountryEnglish = "Canada", ShortCode = "CA" });
                    _context.Country.Add(new Country() { CountryChinese = "佛得角", CountryEnglish = "Cape Verde", ShortCode = "CV" });
                    _context.Country.Add(new Country() { CountryChinese = "开曼群岛", CountryEnglish = "Cayman Islands", ShortCode = "KY" });
                    _context.Country.Add(new Country() { CountryChinese = "中非共和国", CountryEnglish = "Central African Republic", ShortCode = "CF" });
                    _context.Country.Add(new Country() { CountryChinese = "乍得", CountryEnglish = "Chad", ShortCode = "TD" });
                    _context.Country.Add(new Country() { CountryChinese = "智利", CountryEnglish = "Chile", ShortCode = "CL" });
                    _context.Country.Add(new Country() { CountryChinese = "英属印度洋领地", CountryEnglish = "British Indian Ocean Territory", ShortCode = "IO" });
                    _context.Country.Add(new Country() { CountryChinese = "中国", CountryEnglish = "China", ShortCode = "CN" });
                    _context.Country.Add(new Country() { CountryChinese = "可可群岛", CountryEnglish = "Cocos (Keeling) Islands", ShortCode = "CC" });
                    _context.Country.Add(new Country() { CountryChinese = "哥伦比亚", CountryEnglish = "Colombia", ShortCode = "CO" });
                    _context.Country.Add(new Country() { CountryChinese = "科摩罗", CountryEnglish = "Comoros", ShortCode = "KM" });
                    _context.Country.Add(new Country() { CountryChinese = "刚果", CountryEnglish = "Congo", ShortCode = "CG" });
                    _context.Country.Add(new Country() { CountryChinese = "刚果、民主共和国", CountryEnglish = "Congo, the Democratic Republic of the", ShortCode = "CD" });
                    _context.Country.Add(new Country() { CountryChinese = "库克群岛", CountryEnglish = "Cook Islands", ShortCode = "CK" });
                    _context.Country.Add(new Country() { CountryChinese = "哥斯达黎加", CountryEnglish = "Costa Rica", ShortCode = "CR" });
                    _context.Country.Add(new Country() { CountryChinese = "科特迪瓦", CountryEnglish = "Cote d'Ivoire", ShortCode = "CI" });
                    _context.Country.Add(new Country() { CountryChinese = "克罗地亚 (赫尔瓦次卡)", CountryEnglish = "Croatia (Hrvatska)", ShortCode = "HR" });
                    _context.Country.Add(new Country() { CountryChinese = "古巴", CountryEnglish = "Cuba", ShortCode = "CU" });
                    _context.Country.Add(new Country() { CountryChinese = "塞浦路斯", CountryEnglish = "Cyprus", ShortCode = "CY" });
                    _context.Country.Add(new Country() { CountryChinese = "捷克共和国", CountryEnglish = "Czech Republic", ShortCode = "CZ" });
                    _context.Country.Add(new Country() { CountryChinese = "圣诞岛", CountryEnglish = "Christmas Island", ShortCode = "CX" });
                    _context.Country.Add(new Country() { CountryChinese = "丹麦", CountryEnglish = "Denmark", ShortCode = "DK" });
                    _context.Country.Add(new Country() { CountryChinese = "巴西 ", CountryEnglish = "Brazil", ShortCode = "BR" });
                    _context.Country.Add(new Country() { CountryChinese = "博茨瓦纳 ", CountryEnglish = "Botswana", ShortCode = "BW" });
                    _context.Country.Add(new Country() { CountryChinese = "阿尔巴尼亚", CountryEnglish = "Albania", ShortCode = "AL" });
                    _context.Country.Add(new Country() { CountryChinese = "阿尔及利亚", CountryEnglish = "Algeria", ShortCode = "DZ" });
                    _context.Country.Add(new Country() { CountryChinese = "美属萨摩亚", CountryEnglish = "American Samoa", ShortCode = "AS" });
                    _context.Country.Add(new Country() { CountryChinese = "安道尔", CountryEnglish = "Andorra", ShortCode = "AD" });
                    _context.Country.Add(new Country() { CountryChinese = "安哥拉", CountryEnglish = "Angola", ShortCode = "AO" });
                    _context.Country.Add(new Country() { CountryChinese = "安圭拉岛", CountryEnglish = "Anguilla", ShortCode = "AI" });
                    _context.Country.Add(new Country() { CountryChinese = "南极洲", CountryEnglish = "Antarctica", ShortCode = "AQ" });
                    _context.Country.Add(new Country() { CountryChinese = "安提瓜和巴布达", CountryEnglish = "Antigua and Barbuda", ShortCode = "AG" });
                    _context.Country.Add(new Country() { CountryChinese = "阿根廷", CountryEnglish = "Argentina", ShortCode = "AR" });
                    _context.Country.Add(new Country() { CountryChinese = "亚美尼亚", CountryEnglish = "Armenia", ShortCode = "AM" });
                    _context.Country.Add(new Country() { CountryChinese = "阿鲁巴", CountryEnglish = "Aruba", ShortCode = "AW" });
                    _context.Country.Add(new Country() { CountryChinese = "澳大利亚", CountryEnglish = "Australia", ShortCode = "AU" });
                    _context.Country.Add(new Country() { CountryChinese = "布维岛岛", CountryEnglish = "Bouvet Island", ShortCode = "BV" });
                    _context.Country.Add(new Country() { CountryChinese = "奥地利", CountryEnglish = "Austria", ShortCode = "AT" });
                    _context.Country.Add(new Country() { CountryChinese = "巴哈马", CountryEnglish = "Bahamas", ShortCode = "BS" });
                    _context.Country.Add(new Country() { CountryChinese = "巴林", CountryEnglish = "Bahrain", ShortCode = "BH" });
                    _context.Country.Add(new Country() { CountryChinese = "孟加拉国", CountryEnglish = "Bangladesh", ShortCode = "BD" });
                    _context.Country.Add(new Country() { CountryChinese = "巴巴多斯", CountryEnglish = "Barbados", ShortCode = "BB" });
                    _context.Country.Add(new Country() { CountryChinese = "白俄罗斯", CountryEnglish = "Belarus", ShortCode = "BY" });
                    _context.Country.Add(new Country() { CountryChinese = "比利时", CountryEnglish = "Belgium", ShortCode = "BE" });
                    _context.Country.Add(new Country() { CountryChinese = "伯利兹", CountryEnglish = "Belize", ShortCode = "BZ" });
                    _context.Country.Add(new Country() { CountryChinese = "贝宁 ", CountryEnglish = "Benin", ShortCode = "BJ" });
                    _context.Country.Add(new Country() { CountryChinese = "百慕大", CountryEnglish = "Bermuda", ShortCode = "BM" });
                    _context.Country.Add(new Country() { CountryChinese = "不丹", CountryEnglish = "Bhutan", ShortCode = "BT" });
                    _context.Country.Add(new Country() { CountryChinese = "玻利维亚 ", CountryEnglish = "Bolivia", ShortCode = "BO" });
                    _context.Country.Add(new Country() { CountryChinese = "波斯尼亚", CountryEnglish = "Bosnia and Herzegowina", ShortCode = "BA" });
                    _context.Country.Add(new Country() { CountryChinese = "阿塞拜疆", CountryEnglish = "Azerbaijan", ShortCode = "AZ" });
                    _context.Country.Add(new Country() { CountryChinese = "拉托维亚", CountryEnglish = "Latvia", ShortCode = "LV" });
                    _context.Country.Add(new Country() { CountryChinese = "吉布提", CountryEnglish = "Djibouti", ShortCode = "DJ" });
                    _context.Country.Add(new Country() { CountryChinese = "多米尼加共和国  ", CountryEnglish = "Dominican Republic", ShortCode = "DO" });
                    _context.Country.Add(new Country() { CountryChinese = "几内亚比绍", CountryEnglish = "Guinea-Bissau", ShortCode = "GW" });
                    _context.Country.Add(new Country() { CountryChinese = "圭亚那", CountryEnglish = "Guyana", ShortCode = "GY" });
                    _context.Country.Add(new Country() { CountryChinese = "海地", CountryEnglish = "Haiti", ShortCode = "HT" });
                    _context.Country.Add(new Country() { CountryChinese = "赫德和麦克唐纳群岛", CountryEnglish = "Heard and Mc Donald Islands", ShortCode = "HM" });
                    _context.Country.Add(new Country() { CountryChinese = "圣洁看见 (梵蒂冈城市状态)", CountryEnglish = "Holy See (Vatican City State)", ShortCode = "VA" });
                    _context.Country.Add(new Country() { CountryChinese = "洪都拉斯", CountryEnglish = "Honduras", ShortCode = "HN" });
                    _context.Country.Add(new Country() { CountryChinese = "香港", CountryEnglish = "Hong Kong", ShortCode = "HK" });
                    _context.Country.Add(new Country() { CountryChinese = "匈牙利", CountryEnglish = "Hungary", ShortCode = "HU" });
                    _context.Country.Add(new Country() { CountryChinese = "冰岛", CountryEnglish = "Iceland", ShortCode = "IS" });
                    _context.Country.Add(new Country() { CountryChinese = "印度", CountryEnglish = "India", ShortCode = "IN" });
                    _context.Country.Add(new Country() { CountryChinese = "印度尼西亚", CountryEnglish = "Indonesia", ShortCode = "ID" });
                    _context.Country.Add(new Country() { CountryChinese = "伊朗 (伊斯兰共和国)", CountryEnglish = "Iran (Islamic Republic of)", ShortCode = "IR" });
                    _context.Country.Add(new Country() { CountryChinese = "几内亚", CountryEnglish = "Guinea", ShortCode = "GN" });
                    _context.Country.Add(new Country() { CountryChinese = "伊拉克", CountryEnglish = "Iraq", ShortCode = "IQ" });
                    _context.Country.Add(new Country() { CountryChinese = "以色列", CountryEnglish = "Israel", ShortCode = "IL" });
                    _context.Country.Add(new Country() { CountryChinese = "意大利", CountryEnglish = "Italy", ShortCode = "IT" });
                    _context.Country.Add(new Country() { CountryChinese = "牙买加", CountryEnglish = "Jamaica", ShortCode = "JM" });
                    _context.Country.Add(new Country() { CountryChinese = "日本", CountryEnglish = "Japan", ShortCode = "JP" });
                    _context.Country.Add(new Country() { CountryChinese = "约旦", CountryEnglish = "Jordan", ShortCode = "JO" });
                    _context.Country.Add(new Country() { CountryChinese = "哈萨克斯坦", CountryEnglish = "Kazakhstan", ShortCode = "KZ" });
                    _context.Country.Add(new Country() { CountryChinese = "肯尼亚", CountryEnglish = "Kenya", ShortCode = "KE" });
                    _context.Country.Add(new Country() { CountryChinese = "基里巴斯", CountryEnglish = "Kiribati", ShortCode = "KI" });
                    _context.Country.Add(new Country() { CountryChinese = "朝鲜民主人民共和国", CountryEnglish = "Korea, Democratic People's Republic of", ShortCode = "KP" });
                    _context.Country.Add(new Country() { CountryChinese = "大韩民国", CountryEnglish = "Korea, Republic of", ShortCode = "KR" });
                    _context.Country.Add(new Country() { CountryChinese = "科威特", CountryEnglish = "Kuwait", ShortCode = "KW" });
                    _context.Country.Add(new Country() { CountryChinese = "吉尔吉斯斯坦", CountryEnglish = "Kyrgyzstan", ShortCode = "KG" });
                    _context.Country.Add(new Country() { CountryChinese = "爱尔兰", CountryEnglish = "Ireland", ShortCode = "IE" });
                    _context.Country.Add(new Country() { CountryChinese = "多米尼加", CountryEnglish = "Dominica", ShortCode = "DM" });
                    _context.Country.Add(new Country() { CountryChinese = "危地马拉", CountryEnglish = "Guatemala", ShortCode = "GT" });
                    _context.Country.Add(new Country() { CountryChinese = "瓜德罗普", CountryEnglish = "Guadeloupe", ShortCode = "GP" });
                    _context.Country.Add(new Country() { CountryChinese = "东帝汶", CountryEnglish = "East Timor", ShortCode = "TP" });
                    _context.Country.Add(new Country() { CountryChinese = "厄瓜多尔", CountryEnglish = "Ecuador", ShortCode = "EC" });
                    _context.Country.Add(new Country() { CountryChinese = "埃及", CountryEnglish = "Egypt", ShortCode = "EG" });
                    _context.Country.Add(new Country() { CountryChinese = "萨尔瓦多", CountryEnglish = "El Salvador", ShortCode = "SV" });
                    _context.Country.Add(new Country() { CountryChinese = "赤道几内亚", CountryEnglish = "Equatorial Guinea", ShortCode = "GQ" });
                    _context.Country.Add(new Country() { CountryChinese = "厄立特里亚", CountryEnglish = "Eritrea", ShortCode = "ER" });
                    _context.Country.Add(new Country() { CountryChinese = "爱沙尼亚", CountryEnglish = "Estonia", ShortCode = "EE" });
                    _context.Country.Add(new Country() { CountryChinese = "埃塞俄比亚", CountryEnglish = "Ethiopia", ShortCode = "ET" });
                    _context.Country.Add(new Country() { CountryChinese = "福克兰 (马尔维纳斯) 群岛", CountryEnglish = "Falkland Islands (Malvinas)", ShortCode = "FK" });
                    _context.Country.Add(new Country() { CountryChinese = "法罗群岛", CountryEnglish = "Faroe Islands", ShortCode = "FO" });
                    _context.Country.Add(new Country() { CountryChinese = "斐济", CountryEnglish = "Fiji", ShortCode = "FJ" });
                    _context.Country.Add(new Country() { CountryChinese = "芬兰", CountryEnglish = "Finland", ShortCode = "FI" });
                    _context.Country.Add(new Country() { CountryChinese = "关岛", CountryEnglish = "Guam", ShortCode = "GU" });
                    _context.Country.Add(new Country() { CountryChinese = "法国", CountryEnglish = "France", ShortCode = "FR" });
                    _context.Country.Add(new Country() { CountryChinese = "法属圭亚那", CountryEnglish = "French Guiana", ShortCode = "GF" });
                    _context.Country.Add(new Country() { CountryChinese = "法属波利尼西亚", CountryEnglish = "French Polynesia", ShortCode = "PF" });
                    _context.Country.Add(new Country() { CountryChinese = "法国南部领土", CountryEnglish = "French Southern Territories", ShortCode = "TF" });
                    _context.Country.Add(new Country() { CountryChinese = "加蓬", CountryEnglish = "Gabon", ShortCode = "GA" });
                    _context.Country.Add(new Country() { CountryChinese = "冈比亚", CountryEnglish = "Gambia", ShortCode = "GM" });
                    _context.Country.Add(new Country() { CountryChinese = "格鲁吉亚", CountryEnglish = "Georgia", ShortCode = "GE" });
                    _context.Country.Add(new Country() { CountryChinese = "德国", CountryEnglish = "Germany", ShortCode = "DE" });
                    _context.Country.Add(new Country() { CountryChinese = "加纳", CountryEnglish = "Ghana", ShortCode = "GH" });
                    _context.Country.Add(new Country() { CountryChinese = "直布罗陀", CountryEnglish = "Gibraltar", ShortCode = "GI" });
                    _context.Country.Add(new Country() { CountryChinese = "希腊", CountryEnglish = "Greece", ShortCode = "GR" });
                    _context.Country.Add(new Country() { CountryChinese = "格陵兰", CountryEnglish = "Greenland", ShortCode = "GL" });
                    _context.Country.Add(new Country() { CountryChinese = "格林纳达", CountryEnglish = "Grenada", ShortCode = "GD" });
                    _context.Country.Add(new Country() { CountryChinese = "法国, 大都会", CountryEnglish = "France, Metropolitan", ShortCode = "FX" });
                    _context.Country.Add(new Country() { CountryChinese = "津巴布韦", CountryEnglish = "Zimbabwe", ShortCode = "ZW" });
                    _context.SaveChanges();
                }
            }
            catch (Exception)
            {

            }
        }
    }
}
