using RenewalWebsite.Data;
using RenewalWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RenewalWebsite
{
    public class CountrySeeder
    {
        private readonly ApplicationDbContext _context;

        public CountrySeeder(ApplicationDbContext context)
        {
            _context = context;
        }

        public void Seed()
        {
            if (_context.Country.Count() == 0)
            {
                _context.Country.Add(new Country() { CountryChinese = "阿富汗", CountryEnglish = "Afghanistan", ShortCode = "AF", order = 1 });
                _context.Country.Add(new Country() { CountryChinese = "阿尔巴尼亚", CountryEnglish = "Albania", ShortCode = "AL", order = 2 });
                _context.Country.Add(new Country() { CountryChinese = "阿尔及利亚", CountryEnglish = "Algeria", ShortCode = "DZ", order = 3 });
                _context.Country.Add(new Country() { CountryChinese = "美属萨摩亚", CountryEnglish = "American Samoa", ShortCode = "AS", order = 4 });
                _context.Country.Add(new Country() { CountryChinese = "安道尔", CountryEnglish = "Andorra", ShortCode = "AD", order = 5 });
                _context.Country.Add(new Country() { CountryChinese = "安哥拉", CountryEnglish = "Angola", ShortCode = "AO", order = 6 });
                _context.Country.Add(new Country() { CountryChinese = "安圭拉岛", CountryEnglish = "Anguilla", ShortCode = "AI", order = 7 });
                _context.Country.Add(new Country() { CountryChinese = "南极洲", CountryEnglish = "Antarctica", ShortCode = "AQ", order = 8 });
                _context.Country.Add(new Country() { CountryChinese = "安提瓜和巴布达", CountryEnglish = "Antigua and Barbuda", ShortCode = "AG", order = 9 });
                _context.Country.Add(new Country() { CountryChinese = "阿根廷", CountryEnglish = "Argentina", ShortCode = "AR", order = 10 });
                _context.Country.Add(new Country() { CountryChinese = "亚美尼亚", CountryEnglish = "Armenia", ShortCode = "AM", order = 11 });
                _context.Country.Add(new Country() { CountryChinese = "阿鲁巴", CountryEnglish = "Aruba", ShortCode = "AW", order = 12 });
                _context.Country.Add(new Country() { CountryChinese = "澳大利亚", CountryEnglish = "Australia", ShortCode = "AU", order = 13 });
                _context.Country.Add(new Country() { CountryChinese = "奥地利", CountryEnglish = "Austria", ShortCode = "AT", order = 14 });
                _context.Country.Add(new Country() { CountryChinese = "阿塞拜疆", CountryEnglish = "Azerbaijan", ShortCode = "AZ", order = 15 });
                _context.Country.Add(new Country() { CountryChinese = "巴哈马", CountryEnglish = "Bahamas", ShortCode = "BS", order = 16 });
                _context.Country.Add(new Country() { CountryChinese = "巴林", CountryEnglish = "Bahrain", ShortCode = "BH", order = 17 });
                _context.Country.Add(new Country() { CountryChinese = "孟加拉国", CountryEnglish = "Bangladesh", ShortCode = "BD", order = 18 });
                _context.Country.Add(new Country() { CountryChinese = "巴巴多斯", CountryEnglish = "Barbados", ShortCode = "BB", order = 19 });
                _context.Country.Add(new Country() { CountryChinese = "白俄罗斯", CountryEnglish = "Belarus", ShortCode = "BY", order = 20 });
                _context.Country.Add(new Country() { CountryChinese = "比利时", CountryEnglish = "Belgium", ShortCode = "BE", order = 21 });
                _context.Country.Add(new Country() { CountryChinese = "伯利兹", CountryEnglish = "Belize", ShortCode = "BZ", order = 22 });
                _context.Country.Add(new Country() { CountryChinese = "贝宁 ", CountryEnglish = "Benin", ShortCode = "BJ", order = 23 });
                _context.Country.Add(new Country() { CountryChinese = "百慕大", CountryEnglish = "Bermuda", ShortCode = "BM", order = 24 });
                _context.Country.Add(new Country() { CountryChinese = "不丹", CountryEnglish = "Bhutan", ShortCode = "BT", order = 25 });
                _context.Country.Add(new Country() { CountryChinese = "玻利维亚 ", CountryEnglish = "Bolivia", ShortCode = "BO", order = 26 });
                _context.Country.Add(new Country() { CountryChinese = "波斯尼亚", CountryEnglish = "Bosnia and Herzegowina", ShortCode = "BA", order = 27 });
                _context.Country.Add(new Country() { CountryChinese = "博茨瓦纳 ", CountryEnglish = "Botswana", ShortCode = "BW", order = 28 });
                _context.Country.Add(new Country() { CountryChinese = "布维岛岛", CountryEnglish = "Bouvet Island", ShortCode = "BV", order = 29 });
                _context.Country.Add(new Country() { CountryChinese = "巴西 ", CountryEnglish = "Brazil", ShortCode = "BR", order = 30 });
                _context.Country.Add(new Country() { CountryChinese = "英属印度洋领地", CountryEnglish = "British Indian Ocean Territory", ShortCode = "IO", order = 31 });
                _context.Country.Add(new Country() { CountryChinese = "文莱达鲁萨兰国", CountryEnglish = "Brunei Darussalam", ShortCode = "BN", order = 32 });
                _context.Country.Add(new Country() { CountryChinese = "保加利亚", CountryEnglish = "Bulgaria", ShortCode = "BG", order = 33 });
                _context.Country.Add(new Country() { CountryChinese = "布基纳法索", CountryEnglish = "Burkina Faso", ShortCode = "BF", order = 34 });
                _context.Country.Add(new Country() { CountryChinese = "布隆迪", CountryEnglish = "Burundi", ShortCode = "BI", order = 35 });
                _context.Country.Add(new Country() { CountryChinese = "柬埔寨", CountryEnglish = "Cambodia", ShortCode = "KH", order = 36 });
                _context.Country.Add(new Country() { CountryChinese = "喀麦隆", CountryEnglish = "Cameroon", ShortCode = "CM", order = 37 });
                _context.Country.Add(new Country() { CountryChinese = "加拿大", CountryEnglish = "Canada", ShortCode = "CA", order = 38 });
                _context.Country.Add(new Country() { CountryChinese = "佛得角", CountryEnglish = "Cape Verde", ShortCode = "CV", order = 39 });
                _context.Country.Add(new Country() { CountryChinese = "开曼群岛", CountryEnglish = "Cayman Islands", ShortCode = "KY", order = 40 });
                _context.Country.Add(new Country() { CountryChinese = "中非共和国", CountryEnglish = "Central African Republic", ShortCode = "CF", order = 41 });
                _context.Country.Add(new Country() { CountryChinese = "乍得", CountryEnglish = "Chad", ShortCode = "TD", order = 42 });
                _context.Country.Add(new Country() { CountryChinese = "智利", CountryEnglish = "Chile", ShortCode = "CL", order = 43 });
                _context.Country.Add(new Country() { CountryChinese = "中国", CountryEnglish = "China", ShortCode = "CN", order = 44 });
                _context.Country.Add(new Country() { CountryChinese = "圣诞岛", CountryEnglish = "Christmas Island", ShortCode = "CX", order = 45 });
                _context.Country.Add(new Country() { CountryChinese = "可可群岛", CountryEnglish = "Cocos (Keeling) Islands", ShortCode = "CC", order = 46 });
                _context.Country.Add(new Country() { CountryChinese = "哥伦比亚", CountryEnglish = "Colombia", ShortCode = "CO", order = 47 });
                _context.Country.Add(new Country() { CountryChinese = "科摩罗", CountryEnglish = "Comoros", ShortCode = "KM", order = 48 });
                _context.Country.Add(new Country() { CountryChinese = "刚果", CountryEnglish = "Congo", ShortCode = "CG", order = 49 });
                _context.Country.Add(new Country() { CountryChinese = "刚果、民主共和国", CountryEnglish = "Congo, the Democratic Republic of the", ShortCode = "CD", order = 50 });
                _context.Country.Add(new Country() { CountryChinese = "库克群岛", CountryEnglish = "Cook Islands", ShortCode = "CK", order = 51 });
                _context.Country.Add(new Country() { CountryChinese = "哥斯达黎加", CountryEnglish = "Costa Rica", ShortCode = "CR", order = 52 });
                _context.Country.Add(new Country() { CountryChinese = "科特迪瓦", CountryEnglish = "Cote d'Ivoire", ShortCode = "CI", order = 53 });
                _context.Country.Add(new Country() { CountryChinese = "克罗地亚 (赫尔瓦次卡)", CountryEnglish = "Croatia (Hrvatska)", ShortCode = "HR", order = 54 });
                _context.Country.Add(new Country() { CountryChinese = "古巴", CountryEnglish = "Cuba", ShortCode = "CU", order = 55 });
                _context.Country.Add(new Country() { CountryChinese = "塞浦路斯", CountryEnglish = "Cyprus", ShortCode = "CY", order = 56 });
                _context.Country.Add(new Country() { CountryChinese = "捷克共和国", CountryEnglish = "Czech Republic", ShortCode = "CZ", order = 57 });
                _context.Country.Add(new Country() { CountryChinese = "丹麦", CountryEnglish = "Denmark", ShortCode = "DK", order = 58 });
                _context.Country.Add(new Country() { CountryChinese = "吉布提", CountryEnglish = "Djibouti", ShortCode = "DJ", order = 59 });
                _context.Country.Add(new Country() { CountryChinese = "多米尼加", CountryEnglish = "Dominica", ShortCode = "DM", order = 60 });
                _context.Country.Add(new Country() { CountryChinese = "多米尼加共和国  ", CountryEnglish = "Dominican Republic", ShortCode = "DO", order = 61 });
                _context.Country.Add(new Country() { CountryChinese = "东帝汶", CountryEnglish = "East Timor", ShortCode = "TP", order = 62 });
                _context.Country.Add(new Country() { CountryChinese = "厄瓜多尔", CountryEnglish = "Ecuador", ShortCode = "EC", order = 63 });
                _context.Country.Add(new Country() { CountryChinese = "埃及", CountryEnglish = "Egypt", ShortCode = "EG", order = 64 });
                _context.Country.Add(new Country() { CountryChinese = "萨尔瓦多", CountryEnglish = "El Salvador", ShortCode = "SV", order = 65 });
                _context.Country.Add(new Country() { CountryChinese = "赤道几内亚", CountryEnglish = "Equatorial Guinea", ShortCode = "GQ", order = 66 });
                _context.Country.Add(new Country() { CountryChinese = "厄立特里亚", CountryEnglish = "Eritrea", ShortCode = "ER", order = 67 });
                _context.Country.Add(new Country() { CountryChinese = "爱沙尼亚", CountryEnglish = "Estonia", ShortCode = "EE", order = 68 });
                _context.Country.Add(new Country() { CountryChinese = "埃塞俄比亚", CountryEnglish = "Ethiopia", ShortCode = "ET", order = 69 });
                _context.Country.Add(new Country() { CountryChinese = "福克兰 (马尔维纳斯) 群岛", CountryEnglish = "Falkland Islands (Malvinas)", ShortCode = "FK", order = 70 });
                _context.Country.Add(new Country() { CountryChinese = "法罗群岛", CountryEnglish = "Faroe Islands", ShortCode = "FO", order = 71 });
                _context.Country.Add(new Country() { CountryChinese = "斐济", CountryEnglish = "Fiji", ShortCode = "FJ", order = 72 });
                _context.Country.Add(new Country() { CountryChinese = "芬兰", CountryEnglish = "Finland", ShortCode = "FI", order = 73 });
                _context.Country.Add(new Country() { CountryChinese = "法国", CountryEnglish = "France", ShortCode = "FR", order = 74 });
                _context.Country.Add(new Country() { CountryChinese = "法国, 大都会", CountryEnglish = "France, Metropolitan", ShortCode = "FX", order = 75 });
                _context.Country.Add(new Country() { CountryChinese = "法属圭亚那", CountryEnglish = "French Guiana", ShortCode = "GF", order = 76 });
                _context.Country.Add(new Country() { CountryChinese = "法属波利尼西亚", CountryEnglish = "French Polynesia", ShortCode = "PF", order = 77 });
                _context.Country.Add(new Country() { CountryChinese = "法国南部领土", CountryEnglish = "French Southern Territories", ShortCode = "TF", order = 78 });
                _context.Country.Add(new Country() { CountryChinese = "加蓬", CountryEnglish = "Gabon", ShortCode = "GA", order = 79 });
                _context.Country.Add(new Country() { CountryChinese = "冈比亚", CountryEnglish = "Gambia", ShortCode = "GM", order = 80 });
                _context.Country.Add(new Country() { CountryChinese = "格鲁吉亚", CountryEnglish = "Georgia", ShortCode = "GE", order = 81 });
                _context.Country.Add(new Country() { CountryChinese = "德国", CountryEnglish = "Germany", ShortCode = "DE", order = 82 });
                _context.Country.Add(new Country() { CountryChinese = "加纳", CountryEnglish = "Ghana", ShortCode = "GH", order = 83 });
                _context.Country.Add(new Country() { CountryChinese = "直布罗陀", CountryEnglish = "Gibraltar", ShortCode = "GI", order = 84 });
                _context.Country.Add(new Country() { CountryChinese = "希腊", CountryEnglish = "Greece", ShortCode = "GR", order = 85 });
                _context.Country.Add(new Country() { CountryChinese = "格陵兰", CountryEnglish = "Greenland", ShortCode = "GL", order = 86 });
                _context.Country.Add(new Country() { CountryChinese = "格林纳达", CountryEnglish = "Grenada", ShortCode = "GD", order = 87 });
                _context.Country.Add(new Country() { CountryChinese = "瓜德罗普", CountryEnglish = "Guadeloupe", ShortCode = "GP", order = 88 });
                _context.Country.Add(new Country() { CountryChinese = "关岛", CountryEnglish = "Guam", ShortCode = "GU", order = 89 });
                _context.Country.Add(new Country() { CountryChinese = "危地马拉", CountryEnglish = "Guatemala", ShortCode = "GT", order = 90 });
                _context.Country.Add(new Country() { CountryChinese = "几内亚", CountryEnglish = "Guinea", ShortCode = "GN", order = 91 });
                _context.Country.Add(new Country() { CountryChinese = "几内亚比绍", CountryEnglish = "Guinea-Bissau", ShortCode = "GW", order = 92 });
                _context.Country.Add(new Country() { CountryChinese = "圭亚那", CountryEnglish = "Guyana", ShortCode = "GY", order = 93 });
                _context.Country.Add(new Country() { CountryChinese = "海地", CountryEnglish = "Haiti", ShortCode = "HT", order = 94 });
                _context.Country.Add(new Country() { CountryChinese = "赫德和麦克唐纳群岛", CountryEnglish = "Heard and Mc Donald Islands", ShortCode = "HM", order = 95 });
                _context.Country.Add(new Country() { CountryChinese = "圣洁看见 (梵蒂冈城市状态)", CountryEnglish = "Holy See (Vatican City State)", ShortCode = "VA", order = 96 });
                _context.Country.Add(new Country() { CountryChinese = "洪都拉斯", CountryEnglish = "Honduras", ShortCode = "HN", order = 97 });
                _context.Country.Add(new Country() { CountryChinese = "香港", CountryEnglish = "Hong Kong", ShortCode = "HK", order = 98 });
                _context.Country.Add(new Country() { CountryChinese = "匈牙利", CountryEnglish = "Hungary", ShortCode = "HU", order = 99 });
                _context.Country.Add(new Country() { CountryChinese = "冰岛", CountryEnglish = "Iceland", ShortCode = "IS", order = 100 });
                _context.Country.Add(new Country() { CountryChinese = "印度", CountryEnglish = "India", ShortCode = "IN", order = 101 });
                _context.Country.Add(new Country() { CountryChinese = "印度尼西亚", CountryEnglish = "Indonesia", ShortCode = "ID", order = 102 });
                _context.Country.Add(new Country() { CountryChinese = "伊朗 (伊斯兰共和国)", CountryEnglish = "Iran (Islamic Republic of)", ShortCode = "IR", order = 103 });
                _context.Country.Add(new Country() { CountryChinese = "伊拉克", CountryEnglish = "Iraq", ShortCode = "IQ", order = 104 });
                _context.Country.Add(new Country() { CountryChinese = "爱尔兰", CountryEnglish = "Ireland", ShortCode = "IE", order = 105 });
                _context.Country.Add(new Country() { CountryChinese = "以色列", CountryEnglish = "Israel", ShortCode = "IL", order = 106 });
                _context.Country.Add(new Country() { CountryChinese = "意大利", CountryEnglish = "Italy", ShortCode = "IT", order = 107 });
                _context.Country.Add(new Country() { CountryChinese = "牙买加", CountryEnglish = "Jamaica", ShortCode = "JM", order = 108 });
                _context.Country.Add(new Country() { CountryChinese = "日本", CountryEnglish = "Japan", ShortCode = "JP", order = 109 });
                _context.Country.Add(new Country() { CountryChinese = "约旦", CountryEnglish = "Jordan", ShortCode = "JO", order = 110 });
                _context.Country.Add(new Country() { CountryChinese = "哈萨克斯坦", CountryEnglish = "Kazakhstan", ShortCode = "KZ", order = 111 });
                _context.Country.Add(new Country() { CountryChinese = "肯尼亚", CountryEnglish = "Kenya", ShortCode = "KE", order = 112 });
                _context.Country.Add(new Country() { CountryChinese = "基里巴斯", CountryEnglish = "Kiribati", ShortCode = "KI", order = 113 });
                _context.Country.Add(new Country() { CountryChinese = "朝鲜民主人民共和国", CountryEnglish = "Korea, Democratic People's Republic of", ShortCode = "KP", order = 114 });
                _context.Country.Add(new Country() { CountryChinese = "大韩民国", CountryEnglish = "Korea, Republic of", ShortCode = "KR", order = 115 });
                _context.Country.Add(new Country() { CountryChinese = "科威特", CountryEnglish = "Kuwait", ShortCode = "KW", order = 116 });
                _context.Country.Add(new Country() { CountryChinese = "吉尔吉斯斯坦", CountryEnglish = "Kyrgyzstan", ShortCode = "KG", order = 117 });
                _context.Country.Add(new Country() { CountryChinese = "老挝人民民主共和国", CountryEnglish = "Lao People's Democratic Republic", ShortCode = "LA", order = 118 });
                _context.Country.Add(new Country() { CountryChinese = "拉托维亚", CountryEnglish = "Latvia", ShortCode = "LV", order = 119 });
                _context.Country.Add(new Country() { CountryChinese = "黎巴嫩", CountryEnglish = "Lebanon", ShortCode = "LB", order = 120 });
                _context.Country.Add(new Country() { CountryChinese = "莱索托", CountryEnglish = "Lesotho", ShortCode = "LS", order = 121 });
                _context.Country.Add(new Country() { CountryChinese = "利比里亚", CountryEnglish = "Liberia", ShortCode = "LR", order = 122 });
                _context.Country.Add(new Country() { CountryChinese = "阿拉伯利比亚民众国", CountryEnglish = "Libyan Arab Jamahiriya", ShortCode = "LY", order = 123 });
                _context.Country.Add(new Country() { CountryChinese = "列支敦士登", CountryEnglish = "Liechtenstein", ShortCode = "LI", order = 124 });
                _context.Country.Add(new Country() { CountryChinese = "立陶宛", CountryEnglish = "Lithuania", ShortCode = "LT", order = 125 });
                _context.Country.Add(new Country() { CountryChinese = "卢森堡", CountryEnglish = "Luxembourg", ShortCode = "LU", order = 126 });
                _context.Country.Add(new Country() { CountryChinese = "澳门", CountryEnglish = "Macau", ShortCode = "MO", order = 127 });
                _context.Country.Add(new Country() { CountryChinese = "马其顿, 前南斯拉夫共和国", CountryEnglish = "Macedonia, The Former Yugoslav Republic of", ShortCode = "MK", order = 128 });
                _context.Country.Add(new Country() { CountryChinese = "马达加斯加", CountryEnglish = "Madagascar", ShortCode = "MG", order = 129 });
                _context.Country.Add(new Country() { CountryChinese = "马拉维", CountryEnglish = "Malawi", ShortCode = "MW", order = 130 });
                _context.Country.Add(new Country() { CountryChinese = "马来西亚", CountryEnglish = "Malaysia", ShortCode = "MY", order = 131 });
                _context.Country.Add(new Country() { CountryChinese = "马尔代夫", CountryEnglish = "Maldives", ShortCode = "MV", order = 132 });
                _context.Country.Add(new Country() { CountryChinese = "马里", CountryEnglish = "Mali", ShortCode = "ML", order = 133 });
                _context.Country.Add(new Country() { CountryChinese = "马耳他", CountryEnglish = "Malta", ShortCode = "MT", order = 134 });
                _context.Country.Add(new Country() { CountryChinese = "马绍尔群岛", CountryEnglish = "Marshall Islands", ShortCode = "MH", order = 135 });
                _context.Country.Add(new Country() { CountryChinese = "马提尼克岛", CountryEnglish = "Martinique", ShortCode = "MQ", order = 136 });
                _context.Country.Add(new Country() { CountryChinese = "毛里塔尼亚", CountryEnglish = "Mauritania", ShortCode = "MR", order = 137 });
                _context.Country.Add(new Country() { CountryChinese = "毛里求斯", CountryEnglish = "Mauritius", ShortCode = "MU", order = 138 });
                _context.Country.Add(new Country() { CountryChinese = "马约特岛", CountryEnglish = "Mayotte", ShortCode = "YT", order = 139 });
                _context.Country.Add(new Country() { CountryChinese = "墨西哥", CountryEnglish = "Mexico", ShortCode = "MX", order = 140 });
                _context.Country.Add(new Country() { CountryChinese = "密克罗尼西亚、联邦", CountryEnglish = "Micronesia, Federated States of", ShortCode = "FM", order = 141 });
                _context.Country.Add(new Country() { CountryChinese = "摩尔多瓦共和国", CountryEnglish = "Moldova, Republic of", ShortCode = "MD", order = 142 });
                _context.Country.Add(new Country() { CountryChinese = "摩纳哥", CountryEnglish = "Monaco", ShortCode = "MC", order = 143 });
                _context.Country.Add(new Country() { CountryChinese = "蒙古", CountryEnglish = "Mongolia", ShortCode = "MN", order = 144 });
                _context.Country.Add(new Country() { CountryChinese = "蒙特塞拉特", CountryEnglish = "Montserrat", ShortCode = "MS", order = 145 });
                _context.Country.Add(new Country() { CountryChinese = "摩洛哥", CountryEnglish = "Morocco", ShortCode = "MA", order = 146 });
                _context.Country.Add(new Country() { CountryChinese = "莫桑比克", CountryEnglish = "Mozambique", ShortCode = "MZ", order = 147 });
                _context.Country.Add(new Country() { CountryChinese = "缅甸", CountryEnglish = "Myanmar", ShortCode = "MM", order = 148 });
                _context.Country.Add(new Country() { CountryChinese = "纳米比亚", CountryEnglish = "Namibia", ShortCode = "NA", order = 149 });
                _context.Country.Add(new Country() { CountryChinese = "瑙鲁", CountryEnglish = "Nauru", ShortCode = "NR", order = 150 });
                _context.Country.Add(new Country() { CountryChinese = "尼泊尔", CountryEnglish = "Nepal", ShortCode = "NP", order = 151 });
                _context.Country.Add(new Country() { CountryChinese = "荷兰", CountryEnglish = "Netherlands", ShortCode = "NL", order = 152 });
                _context.Country.Add(new Country() { CountryChinese = "荷属安的列斯群岛", CountryEnglish = "Netherlands Antilles", ShortCode = "AN", order = 153 });
                _context.Country.Add(new Country() { CountryChinese = "新喀里多尼亚", CountryEnglish = "New Caledonia", ShortCode = "NC", order = 154 });
                _context.Country.Add(new Country() { CountryChinese = "新西兰", CountryEnglish = "New Zealand", ShortCode = "NZ", order = 155 });
                _context.Country.Add(new Country() { CountryChinese = "尼加拉瓜", CountryEnglish = "Nicaragua", ShortCode = "NI", order = 156 });
                _context.Country.Add(new Country() { CountryChinese = "尼日尔", CountryEnglish = "Niger", ShortCode = "NE", order = 157 });
                _context.Country.Add(new Country() { CountryChinese = "尼日利亚", CountryEnglish = "Nigeria", ShortCode = "NG", order = 158 });
                _context.Country.Add(new Country() { CountryChinese = "纽埃", CountryEnglish = "Niue", ShortCode = "NU", order = 159 });
                _context.Country.Add(new Country() { CountryChinese = "诺福克岛", CountryEnglish = "Norfolk Island", ShortCode = "NF", order = 160 });
                _context.Country.Add(new Country() { CountryChinese = "北马里亚纳群岛", CountryEnglish = "Northern Mariana Islands", ShortCode = "MP", order = 161 });
                _context.Country.Add(new Country() { CountryChinese = "挪威", CountryEnglish = "Norway", ShortCode = "NO", order = 162 });
                _context.Country.Add(new Country() { CountryChinese = "阿曼", CountryEnglish = "Oman", ShortCode = "OM", order = 163 });
                _context.Country.Add(new Country() { CountryChinese = "巴基斯坦", CountryEnglish = "Pakistan", ShortCode = "PK", order = 164 });
                _context.Country.Add(new Country() { CountryChinese = "帕劳", CountryEnglish = "Palau", ShortCode = "PW", order = 165 });
                _context.Country.Add(new Country() { CountryChinese = "巴拿马", CountryEnglish = "Panama", ShortCode = "PA", order = 166 });
                _context.Country.Add(new Country() { CountryChinese = "巴布亚新几内亚", CountryEnglish = "Papua New Guinea", ShortCode = "PG", order = 167 });
                _context.Country.Add(new Country() { CountryChinese = "巴拉圭", CountryEnglish = "Paraguay", ShortCode = "PY", order = 168 });
                _context.Country.Add(new Country() { CountryChinese = "秘鲁", CountryEnglish = "Peru", ShortCode = "PE", order = 169 });
                _context.Country.Add(new Country() { CountryChinese = "菲律宾", CountryEnglish = "Philippines", ShortCode = "PH", order = 170 });
                _context.Country.Add(new Country() { CountryChinese = "皮特凯恩", CountryEnglish = "Pitcairn", ShortCode = "PN", order = 171 });
                _context.Country.Add(new Country() { CountryChinese = "波兰", CountryEnglish = "Poland", ShortCode = "PL", order = 172 });
                _context.Country.Add(new Country() { CountryChinese = "葡萄牙", CountryEnglish = "Portugal", ShortCode = "PT", order = 173 });
                _context.Country.Add(new Country() { CountryChinese = "波多黎各", CountryEnglish = "Puerto Rico", ShortCode = "PR", order = 174 });
                _context.Country.Add(new Country() { CountryChinese = "卡塔尔", CountryEnglish = "Qatar", ShortCode = "QA", order = 175 });
                _context.Country.Add(new Country() { CountryChinese = "留尼旺", CountryEnglish = "Reunion", ShortCode = "RE", order = 176 });
                _context.Country.Add(new Country() { CountryChinese = "罗马尼亚", CountryEnglish = "Romania", ShortCode = "RO", order = 177 });
                _context.Country.Add(new Country() { CountryChinese = "俄罗斯联邦", CountryEnglish = "Russian Federation", ShortCode = "RU", order = 178 });
                _context.Country.Add(new Country() { CountryChinese = "卢旺达", CountryEnglish = "Rwanda", ShortCode = "RW", order = 179 });
                _context.Country.Add(new Country() { CountryChinese = "圣基茨和尼维斯", CountryEnglish = "Saint Kitts and Nevis", ShortCode = "KN", order = 180 });
                _context.Country.Add(new Country() { CountryChinese = "圣卢西亚", CountryEnglish = "Saint LUCIA", ShortCode = "LC", order = 181 });
                _context.Country.Add(new Country() { CountryChinese = "圣文森特和格林纳丁斯", CountryEnglish = "Saint Vincent and the Grenadines", ShortCode = "VC", order = 182 });
                _context.Country.Add(new Country() { CountryChinese = "萨摩亚", CountryEnglish = "Samoa", ShortCode = "WS", order = 183 });
                _context.Country.Add(new Country() { CountryChinese = "圣马力诺", CountryEnglish = "San Marino", ShortCode = "SM", order = 184 });
                _context.Country.Add(new Country() { CountryChinese = "圣多美和普林西比", CountryEnglish = "Sao Tome and Principe", ShortCode = "ST", order = 185 });
                _context.Country.Add(new Country() { CountryChinese = "沙特阿拉伯", CountryEnglish = "Saudi Arabia", ShortCode = "SA", order = 186 });
                _context.Country.Add(new Country() { CountryChinese = "塞内加尔", CountryEnglish = "Senegal", ShortCode = "SN", order = 187 });
                _context.Country.Add(new Country() { CountryChinese = "塞舌尔", CountryEnglish = "Seychelles", ShortCode = "SC", order = 188 });
                _context.Country.Add(new Country() { CountryChinese = "塞拉利昂", CountryEnglish = "Sierra Leone", ShortCode = "SL", order = 189 });
                _context.Country.Add(new Country() { CountryChinese = "新加坡", CountryEnglish = "Singapore", ShortCode = "SG", order = 190 });
                _context.Country.Add(new Country() { CountryChinese = "斯洛伐克 (斯洛伐克共和国)", CountryEnglish = "Slovakia (Slovak Republic)", ShortCode = "SK", order = 191 });
                _context.Country.Add(new Country() { CountryChinese = "斯洛文尼亚", CountryEnglish = "Slovenia", ShortCode = "SI", order = 192 });
                _context.Country.Add(new Country() { CountryChinese = "所罗门群岛", CountryEnglish = "Solomon Islands", ShortCode = "SB", order = 193 });
                _context.Country.Add(new Country() { CountryChinese = "索马里", CountryEnglish = "Somalia", ShortCode = "SO", order = 194 });
                _context.Country.Add(new Country() { CountryChinese = "南非", CountryEnglish = "South Africa", ShortCode = "ZA", order = 195 });
                _context.Country.Add(new Country() { CountryChinese = "南乔治亚岛和南三明治群岛", CountryEnglish = "South Georgia and the South Sandwich Islands", ShortCode = "GS", order = 196 });
                _context.Country.Add(new Country() { CountryChinese = "西班牙", CountryEnglish = "Spain", ShortCode = "ES", order = 197 });
                _context.Country.Add(new Country() { CountryChinese = "斯里兰卡", CountryEnglish = "Sri Lanka", ShortCode = "LK", order = 198 });
                _context.Country.Add(new Country() { CountryChinese = "圣赫勒拿", CountryEnglish = "St. Helena", ShortCode = "SH", order = 199 });
                _context.Country.Add(new Country() { CountryChinese = "圣皮埃尔和圣皮埃尔", CountryEnglish = "St. Pierre and Miquelon", ShortCode = "PM", order = 200 });
                _context.Country.Add(new Country() { CountryChinese = "苏丹", CountryEnglish = "Sudan", ShortCode = "SD", order = 201 });
                _context.Country.Add(new Country() { CountryChinese = "苏里南", CountryEnglish = "Suriname", ShortCode = "SR", order = 202 });
                _context.Country.Add(new Country() { CountryChinese = "斯瓦尔巴特和扬马延岛", CountryEnglish = "Svalbard and Jan Mayen Islands", ShortCode = "SJ", order = 203 });
                _context.Country.Add(new Country() { CountryChinese = "斯威士兰", CountryEnglish = "Swaziland", ShortCode = "SZ", order = 204 });
                _context.Country.Add(new Country() { CountryChinese = "瑞典", CountryEnglish = "Sweden", ShortCode = "SE", order = 205 });
                _context.Country.Add(new Country() { CountryChinese = "瑞士", CountryEnglish = "Switzerland", ShortCode = "CH", order = 206 });
                _context.Country.Add(new Country() { CountryChinese = "阿拉伯叙利亚共和国", CountryEnglish = "Syrian Arab Republic", ShortCode = "SY", order = 207 });
                _context.Country.Add(new Country() { CountryChinese = "中国台湾省", CountryEnglish = "Taiwan, Province of China", ShortCode = "TW", order = 208 });
                _context.Country.Add(new Country() { CountryChinese = "塔吉克斯坦", CountryEnglish = "Tajikistan", ShortCode = "TJ", order = 209 });
                _context.Country.Add(new Country() { CountryChinese = "坦桑尼亚联合共和国", CountryEnglish = "Tanzania, United Republic of", ShortCode = "TZ", order = 210 });
                _context.Country.Add(new Country() { CountryChinese = "泰国", CountryEnglish = "Thailand", ShortCode = "TH", order = 211 });
                _context.Country.Add(new Country() { CountryChinese = "多哥", CountryEnglish = "Togo", ShortCode = "TG", order = 212 });
                _context.Country.Add(new Country() { CountryChinese = "托克劳", CountryEnglish = "Tokelau", ShortCode = "TK", order = 213 });
                _context.Country.Add(new Country() { CountryChinese = "汤加", CountryEnglish = "Tonga", ShortCode = "TO", order = 214 });
                _context.Country.Add(new Country() { CountryChinese = "特立尼达和多巴哥", CountryEnglish = "Trinidad and Tobago", ShortCode = "TT", order = 215 });
                _context.Country.Add(new Country() { CountryChinese = "突尼斯", CountryEnglish = "Tunisia", ShortCode = "TN", order = 216 });
                _context.Country.Add(new Country() { CountryChinese = "土耳其", CountryEnglish = "Turkey", ShortCode = "TR", order = 217 });
                _context.Country.Add(new Country() { CountryChinese = "土库曼斯坦", CountryEnglish = "Turkmenistan", ShortCode = "TM", order = 218 });
                _context.Country.Add(new Country() { CountryChinese = "特克斯和凯科斯群岛", CountryEnglish = "Turks and Caicos Islands", ShortCode = "TC", order = 219 });
                _context.Country.Add(new Country() { CountryChinese = "图瓦卢", CountryEnglish = "Tuvalu", ShortCode = "TV", order = 220 });
                _context.Country.Add(new Country() { CountryChinese = "乌干达", CountryEnglish = "Uganda", ShortCode = "UG", order = 221 });
                _context.Country.Add(new Country() { CountryChinese = "乌克兰", CountryEnglish = "Ukraine", ShortCode = "UA", order = 222 });
                _context.Country.Add(new Country() { CountryChinese = "阿拉伯联合酋长国", CountryEnglish = "United Arab Emirates", ShortCode = "AE", order = 223 });
                _context.Country.Add(new Country() { CountryChinese = "英国", CountryEnglish = "United Kingdom", ShortCode = "GB", order = 224 });
                _context.Country.Add(new Country() { CountryChinese = "美国", CountryEnglish = "United States", ShortCode = "US", order = 225 });
                _context.Country.Add(new Country() { CountryChinese = "美国次要离岛", CountryEnglish = "United States Minor Outlying Islands", ShortCode = "UM", order = 226 });
                _context.Country.Add(new Country() { CountryChinese = "乌拉圭", CountryEnglish = "Uruguay", ShortCode = "UY", order = 227 });
                _context.Country.Add(new Country() { CountryChinese = "乌兹别克斯坦", CountryEnglish = "Uzbekistan", ShortCode = "UZ", order = 228 });
                _context.Country.Add(new Country() { CountryChinese = "瓦努阿图", CountryEnglish = "Vanuatu", ShortCode = "VU", order = 229 });
                _context.Country.Add(new Country() { CountryChinese = "委内瑞拉", CountryEnglish = "Venezuela", ShortCode = "VE", order = 230 });
                _context.Country.Add(new Country() { CountryChinese = "越南", CountryEnglish = "Viet Nam", ShortCode = "VN", order = 231 });
                _context.Country.Add(new Country() { CountryChinese = "维京群岛 (英国)", CountryEnglish = "Virgin Islands (British)", ShortCode = "VG", order = 232 });
                _context.Country.Add(new Country() { CountryChinese = "维京群岛 (美国)", CountryEnglish = "Virgin Islands (U.S.)", ShortCode = "VI", order = 233 });
                _context.Country.Add(new Country() { CountryChinese = "沃利斯和富图纳群岛", CountryEnglish = "Wallis and Futuna Islands", ShortCode = "WF", order = 234 });
                _context.Country.Add(new Country() { CountryChinese = "西撒哈拉", CountryEnglish = "Western Sahara", ShortCode = "EH", order = 235 });
                _context.Country.Add(new Country() { CountryChinese = "也门", CountryEnglish = "Yemen", ShortCode = "YE", order = 236 });
                _context.Country.Add(new Country() { CountryChinese = "南斯拉夫", CountryEnglish = "Yugoslavia", ShortCode = "YU", order = 237 });
                _context.Country.Add(new Country() { CountryChinese = "赞比亚", CountryEnglish = "Zambia", ShortCode = "ZM", order = 238 });
                _context.Country.Add(new Country() { CountryChinese = "津巴布韦", CountryEnglish = "Zimbabwe", ShortCode = "ZW", order = 239 });
                _context.SaveChanges();
            }
        }
    }
}
